# Clippy configuration
# See: https://rust-lang.github.io/rust-clippy/master/

# Lint configuration
too-many-arguments-threshold = 10

# Enable specific lints
msrv = "1.51.0"
cognitive-complexity-threshold = 25
type-complexity-threshold = 500
enum-variant-size-threshold = 200
excessive-nesting-threshold = 6
