edition = "2021"
newline_style = "Unix"
max_width = 100
use_small_heuristics = "Default"
reorder_imports = true

# The following features require nightly, commented out for stable compatibility
# imports_granularity = "Crate"
# normalize_comments = true
# wrap_comments = true
# format_code_in_doc_comments = true
