[package]
exclude = [
    "python/",
    "chemfst-py/",
    "*.fst",
    "__pycache__/",
    "*.pyc",
    "*.pyo",
    "*.so",
    "examples.py",
    "test_*.py",
    "simple_test.py",
    "pyproject.toml",
    ".venv/",
    ".ropeproject/",
]
include = [
    "src/**/*",
    "tests/**/*",
    "Cargo.toml",
    "README.md",
    "LICENSE",
    "CHANGELOG.md",
    "rustfmt.toml",
]