name: Python CI

on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Python Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/
            chemfst-py/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
        if: runner.os != 'Windows'

      - name: Cache Rust dependencies (Windows)
        uses: actions/cache@v3
        with:
          path: |
            C:\Users\runneradmin\.cargo\registry
            C:\Users\runneradmin\.cargo\git
            target\
            chemfst-py\target\
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
        if: runner.os == 'Windows'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install maturin pytest

      - name: Build Python package
        run: |
          maturin build --manifest-path chemfst-py/Cargo.toml --out dist
          python -m pip install dist/*.whl

      - name: Verify test data file exists (Unix)
        run: |
          if [ ! -f "data/chemical_names.txt" ]; then
            echo "Error: data/chemical_names.txt not found in repository"
            echo "This file should be present in the repository"
            exit 1
          fi
          echo "✅ Found existing data/chemical_names.txt"
          echo "File contents:"
          head -5 data/chemical_names.txt
          echo "... ($(wc -l < data/chemical_names.txt) total lines)"
        shell: bash
        if: runner.os != 'Windows'

      - name: Verify test data file exists (Windows)
        run: |
          if (!(Test-Path "data\chemical_names.txt")) {
            Write-Host "Error: data\chemical_names.txt not found in repository"
            Write-Host "This file should be present in the repository"
            exit 1
          }
          Write-Host "✅ Found existing data\chemical_names.txt"
          Write-Host "File contents:"
          Get-Content "data\chemical_names.txt" -Head 5
          $lineCount = (Get-Content "data\chemical_names.txt" | Measure-Object -Line).Lines
          Write-Host "... ($lineCount total lines)"
        shell: powershell
        if: runner.os == 'Windows'

      - name: Run Python tests
        run: python -m pytest python/tests/ -v --tb=short

      - name: Test Python examples
        run: |
          echo "Testing demo example..."
          python python/examples/demo.py
          echo "Demo completed successfully!"

  coverage:
    name: Python Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install maturin pytest pytest-cov

      - name: Build Python package for coverage
        run: |
          maturin build --manifest-path chemfst-py/Cargo.toml --out dist
          python -m pip install dist/*.whl

      - name: Verify test data file exists (Unix)
        run: |
          if [ ! -f "data/chemical_names.txt" ]; then
            echo "Error: data/chemical_names.txt not found in repository"
            echo "This file should be present in the repository"
            exit 1
          fi
          echo "✅ Found existing data/chemical_names.txt"
          echo "File contents:"
          head -5 data/chemical_names.txt
          echo "... ($(wc -l < data/chemical_names.txt) total lines)"
        shell: bash
        if: runner.os != 'Windows'

      - name: Verify test data file exists (Windows)
        run: |
          if (!(Test-Path "data\chemical_names.txt")) {
            Write-Host "Error: data\chemical_names.txt not found in repository"
            Write-Host "This file should be present in the repository"
            exit 1
          }
          Write-Host "✅ Found existing data\chemical_names.txt"
          Write-Host "File contents:"
          Get-Content "data\chemical_names.txt" -Head 5
          $lineCount = (Get-Content "data\chemical_names.txt" | Measure-Object -Line).Lines
          Write-Host "... ($lineCount total lines)"
        shell: powershell
        if: runner.os == 'Windows'

      - name: Run tests with coverage
        run: python -m pytest python/tests/ --cov=chemfst --cov-report=xml --cov-report=term-missing -v

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: python
          name: python-coverage
